### ISSUE TITLE
Add css, html and js linter

### ISSUE THREAD

**Issue by casassg** [hackupc/subscribe#16]
- [x] Add linter for css 
- [x] Add linter for js
- [x] Add linter for html
- [x] Add run command to run all linters
- [x] Add travis to run linters every time
- [x] Add `.editorconfig` file to match linter config. See http://editorconfig.org/

**Comment by casassg** [comment]
https://houndci.com/ Worth checking? @wailingtam

**Comment by wailingtam** [comment]
@casassg  Sadly it doesn't give support to html. And I chose `sass-lint` over `scss-lint` (which is what hound uses) because of this:

> The Sass core team is now building Sass in Dart instead of Ruby, and will no longer be maintaining the Ruby implementation unless a maintainer steps up to help. Since the SCSS-Lint project relies on the Ruby Sass implementation, this means it will eventually not support the latest Sass features and bug fixes.

So we can try to use it for Javascript if you want :)

**Comment by casassg** [comment]
Travis is giving errors... could you please check again?

**Comment by wailingtam** [comment]
It is failing because there're styling errors

**Comment by wailingtam** [comment]
But it is working fine as I can see

**Comment by casassg** [comment]
I know but there's more errors:

- iojs, is failing for other reasons
- it cant find htmlint


see: https://travis-ci.org/hackupc/subscribe/jobs/234580694

**Comment by casassg** [comment]
finally closed in #24
