### ISSUE TITLE
Change background picture

### ISSUE THREAD

**Issue by casassg** [hackupc/subscribe#3]
Not sure about current background picture... Accepting suggestions for alternatives

**Comment by casassg** [comment]
@elena20ruiz can submit here the other picture?

**Comment by elena20ruiz** [comment]
![bg-bandw](https://cloud.githubusercontent.com/assets/15120635/26261128/4e54fb7a-3cd0-11e7-8982-da1958119b28.jpg)

Si vols, puc probar el mateix, pero en color

**Comment by elena20ruiz** [comment]
@casassg

**Comment by casassg** [comment]
@elena20ruiz i la altre que tenies? la que tenies abans...

**Comment by elena20ruiz** [comment]
La del mockup? @casassg

**Comment by elena20ruiz** [comment]
![fondo](https://cloud.githubusercontent.com/assets/15120635/26262157/1ee4b93a-3cd4-11e7-9b0b-b1d2e557f94c.png)

**Comment by casassg** [comment]
@elena20ruiz pots passar la imatge de fons sense el pixelat? i en b&w

**Comment by elena20ruiz** [comment]
![fondo-op1](https://cloud.githubusercontent.com/assets/15120635/26265278/ccf09358-3ce0-11e7-9688-ce5a4b9e12d9.png)

**Comment by AsLogd** [comment]
I like the current one. The only problem I see is that it has high brightness and white zones make text difficult to read. I would add a background to the div to improve readability
![bg](https://cloud.githubusercontent.com/assets/6876725/26266171/8391ca7a-3ce4-11e7-9085-8dcc2c828603.png)

**Comment by casassg** [comment]
the initial one had white background to avoid this (cc @dasilvacontin for mention)

**Comment by casassg** [comment]
changed in #14
