### ISSUE TITLE
Improve imagemin perfomance

### ISSUE THREAD

**Issue by casassg** [hackupc/subscribe#30]
Image minifier plugin is having a poor performance. Try to improve compression rate replacing the compressor plugin. Replace to use `imagemin` instead of `imagemin-newer` maybe? (more configurable)

**Comment by casassg** [comment]
@AsLogd could you take a look at this?

**Comment by ofpau** [comment]
I just tried to compress the background using `imagemin` with a couple of its plugins for png and had no luck (no apparent gain with respect to `imagemin`).
