### ISSUE TITLE
Left align text in description

### ISSUE THREAD

**Issue by casassg** [hackupc/subscribe#35]
Discussion started with @dasilvacontin on slack. Moving this here. 

Pro left align: Not moving around text while changing  lenny faces

Con: I don't like how it looks that much.

Middleground: Normalize lenny faces length adding spaces so that it doesn't move when changing?

**Comment by dasilvacontin** [comment]
I also mentioned moving the emoji alone a line above.

**Comment by casassg** [comment]
@dasilvacontin See #38

**Comment by casassg** [comment]
Closed in #38
