### ISSUE TITLE
Problem with 16:9 screens

### ISSUE THREAD

**Issue by AlbertSuarez** [hackupc/subscribe#41]
I have a little problem seeing the beta web page with the footer.

![screenshot from 2017-05-27 18 33 13](https://cloud.githubusercontent.com/assets/15660893/26522906/16df29c2-430b-11e7-97fb-105a44d26b38.png)

**Comment by casassg** [comment]
Lol. Not even sure how to solve this. @AsLogd @wailingtam @dasilvacontin is there any css max-heigh conditional available for this?

**Comment by AsLogd** [comment]
I guess you could set a div 100% height with a min-height. So it will fill out everything except when its less than the pixels it neds to fit (thin will overflow causing scroll)
To make the height100% work you have to set it to all parents. If nobody does i'll try to fix tonight

**Comment by casassg** [comment]
Not sure what do you mean by this
