### ISSUE TITLE
Change lenny faces dynamically

### ISSUE THREAD

**Issue by casassg** [hackupc/subscribe#8]
By @AlbertSuarez 

( ͡ᵔ ͜ʖ ͡ᵔ )
ᕦ(ò_óˇ)ᕤ
( ͡° ͜ʖ ͡°)
(ᵔᴥᵔ)
\ (•◡•) /

Animate this replacing

**Comment by casassg** [comment]
WIP in #11

**Comment by AsLogd** [comment]
I have a code somewhere to do just this, in case you want it (not difficult nonetheless)

**Comment by casassg** [comment]
@AsLogd See PR #11
